---
title: "DataRt"
author: "Learning Curve"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
par(mar=c(0,0,0,0))
pie(abs(rnorm(100)) , radius=10 , border="transparent" , xlim=c(0,5) )
 
```


```{r}
# generate pairs of x-y values
theta = seq(0, pi, length = 300)
x = cos(theta)
y = sin(theta)
 
# set graphical parameters
op = par(bg = "black", mar = rep(0.5, 4))
 
# plot
plot(x, y, type = 'n')
segments(rep(0, 299), rep(0, 299), x[1:299] * runif(299, 0.7), 
         y[1:299] * runif(299, 0.7), 
         col = hsv(runif(299, 0.45, 0.55), 1, 1, runif(299, 0.5)), 
         lwd = 5*runif(299))
 
```


```{r}
theta = seq(-2 * pi, 2 * pi, length = 300)
x = cos(theta)
y = x + sin(theta) 
 
# set graphical parameters
op = par(bg = "black", mar = rep(0.1, 4))
 
# plot
plot(x, y, type = "n", xlim = c(-8, 8), ylim = c(-1.5, 1.5))
for (i in seq(-2*pi, 2*pi, length = 100))
{
  lines(i*x, y, col = hsv(runif(1, 0.85, 0.95), 1, 1, runif(1, 0.2, 0.5)), 
        lwd = sample(seq(.5, 3, length = 10), 1))          
}
 
```

